apiVersion: apps/v1
kind: Deployment
metadata:
  name: lok-ikj
  namespace: marwan-dev
  labels:
    app: lok-ikj
    developer: lok
    purpose: lmn
spec:
  selector:
    matchLabels:
      app: ikj
  replicas: 1
  template:
    metadata:
      labels:
        app: ikj
    spec:
      containers:
        - name: ikj-lmn
          image: quay.io/idp_org/lok-ikj:lmn:sha256:6273dc025d4ae60826ce4c40790e4adaf2f2824731b75d8a78ddb43b99b1c0bf
