apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazza-ferrityfckya
  namespace: marwan-dev
  labels:
    app: bazza-ferrityfckya
    developer: bazza
    purpose: ffy
spec:
  selector:
    matchLabels:
      app: ferrityfckya
  replicas: 1
  template:
    metadata:
      labels:
        app: ferrityfckya
    spec:
      containers:
        - name: ferrityfckya-ffy
          image: quay.io/idp_org/bazza-ferrityfckya:ffy:sha256:2bf63e770578d622c758f4798337d9816cc2f298b34956a80113a272100fb8e9
