apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogopowerrangers-internal
  namespace: marwan-dev
  labels:
    app: gogopowerrangers-internal
    developer: gogopowerrangers
    purpose: development
spec:
  selector:
    matchLabels:
      app: internal
  replicas: 1
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
        - name: internal-development
          image:
            quay.io/idp_org/gogopowerrangers-internal:development:
