apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-my-react
  namespace: marwan-dev
  labels:
    app: ryu-my-react
    developer: ryu
    purpose: test
spec:
  selector:
    matchLabels:
      app: my-react
  replicas: 1
  template:
    metadata:
      labels:
        app: my-react
    spec:
      containers:
        - name: my-react-test
          image: quay.io/idp_org/ryu-my-react:test:sha256:e1a5c9bba5fe53ecd2c010923fbffe7ede532c65916219913bec8541f93f1b6a
