apiVersion: apps/v1
kind: Deployment
metadata:
  name: werd-wget
  namespace: marwan-dev
  labels:
    app: werd-wget
    developer: werd
    purpose: hopped
spec:
  selector:
    matchLabels:
      app: wget
  replicas: 1
  template:
    metadata:
      labels:
        app: wget
    spec:
      containers:
        - name: wget-hopped
          image: quay.io/idp_org/werd-wget:hopped:sha256:877b17c41d572cb22e7f766c4c31856992c6e63c7254320f8d2b230641e7b22f
