apiVersion: apps/v1
kind: Deployment
metadata:
  name: eee-hellos
  namespace: marwan-dev
  labels:
    app: eee-hellos
    developer: eee
    purpose: yad
spec:
  selector:
    matchLabels:
      app: hellos
  replicas: 1
  template:
    metadata:
      labels:
        app: hellos
    spec:
      containers:
        - name: hellos-yad
          image: quay.io/idp_org/eee-hellos:yad:sha256:945679b681937b4d2fff52d52101bc54806e2bc87d6ba8e377bb5349987973f7
