apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes-nodd
  namespace: marwan-dev
  labels:
    app: nodes-nodd
    developer: nodes
    purpose: node
spec:
  selector:
    matchLabels:
      app: nodd
  replicas: 1
  template:
    metadata:
      labels:
        app: nodd
    spec:
      containers:
        - name: nodd-node
          image: quay.io/idp_org/nodes-nodd:node:sha256:7d834f32c1633b881620daee2bcaf2e4c3173361fe94492fb9330688c8f4116b
