apiVersion: apps/v1
kind: Deployment
metadata:
  name: paw-paw
  namespace: marwan-dev
  labels:
    app: paw-paw
    developer: paw
    purpose: build
spec:
  selector:
    matchLabels:
      app: paw
  replicas: 1
  template:
    metadata:
      labels:
        app: paw
    spec:
      containers:
        - name: paw-build
          image: quay.io/idp_org/paw-paw:build:sha256:1c28fb094ad2bfca894c57319e113a75dac69d65377e2bea5d76846a9c62b2ff
