apiVersion: apps/v1
kind: Deployment
metadata:
  name: adds-asdad
  namespace: marwan-dev
  labels:
    app: adds-asdad
    developer: adds
    purpose: asd
spec:
  selector:
    matchLabels:
      app: asdad
  replicas: 1
  template:
    metadata:
      labels:
        app: asdad
    spec:
      containers:
        - name: asdad-asd
          image: quay.io/idp_org/adds-asdad:asd:sha256:7dccf63a42ee1cddeafccc4daec2af6feab24d5178e99e2a145013536b5e5c75
