apiVersion: apps/v1
kind: Deployment
metadata:
  name: afdd-whynowork
  namespace: marwan-dev
  labels:
    app: afdd-whynowork
    developer: afdd
    purpose: purpose
spec:
  selector:
    matchLabels:
      app: whynowork
  replicas: 1
  template:
    metadata:
      labels:
        app: whynowork
    spec:
      containers:
        - name: whynowork-purpose
          image: quay.io/idp_org/afdd-whynowork:purpose:sha256:4224d2169cd584fd3b6ebc97286d2e67e51b33c3607f1369c8ef982ade08f3ae
