apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaka-zulu
  namespace: marwan-dev
  labels:
    app: shaka-zulu
    developer: shaka
    purpose: invade
spec:
  selector:
    matchLabels:
      app: zulu
  replicas: 1
  template:
    metadata:
      labels:
        app: zulu
    spec:
      containers:
        - name: zulu-invade
          image: quay.io/idp_org/shaka-zulu:invade:sha256:615e35cfeb0ecc9305caf6868d5ae4251380e329b3fbb57d07122d377e53c30e
