apiVersion: apps/v1
kind: Deployment
metadata:
  name: baza-scanneryscanscan
  namespace: marwan-dev
  labels:
    app: baza-scanneryscanscan
    developer: baza
    purpose: fckya
spec:
  selector:
    matchLabels:
      app: scanneryscanscan
  replicas: 1
  template:
    metadata:
      labels:
        app: scanneryscanscan
    spec:
      containers:
        - name: scanneryscanscan-fckya
          image: quay.io/idp_org/baza-scanneryscanscan:fckya:sha256:290c18819eb4710230b71be372ba3470a2e95ed67cb15287b3d859f60f891a26
