apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-no-reg
  namespace: marwan-dev
  labels:
    app: registry-no-reg
    developer: registry
    purpose: reg
spec:
  selector:
    matchLabels:
      app: no-reg
  replicas: 1
  template:
    metadata:
      labels:
        app: no-reg
    spec:
      containers:
        - name: no-reg-reg
          image: quay.io/idp_org/registry-no-reg:reg:sha256:074b62aa5c113a7c6f5ec457cb5680d82e7cafbb4a24abd75c53bbbc3f2e6496
