apiVersion: apps/v1
kind: Deployment
metadata:
  name: qd-asd
  namespace: marwan-dev
  labels:
    app: qd-asd
    developer: qd
    purpose: as
spec:
  selector:
    matchLabels:
      app: asd
  replicas: 1
  template:
    metadata:
      labels:
        app: asd
    spec:
      containers:
        - name: asd-as
          image: quay.io/idp_org/qd-asd:as:sha256:1d825eea2ce69e67b9f80803dbe13904f0c1ff7875dcd108323025469683ea59
