apiVersion: apps/v1
kind: Deployment
metadata:
  name: cucumber-cucumber
  namespace: marwan-dev
  labels:
    app: cucumber-cucumber
    developer: cucumber
    purpose: cucumber
spec:
  selector:
    matchLabels:
      app: cucumber
  replicas: 1
  template:
    metadata:
      labels:
        app: cucumber
    spec:
      containers:
        - name: cucumber-cucumber
          image: quay.io/idp_org/cucumber-cucumber:cucumber:sha256:621a2f862d5354822e444ecea783cc52fd13e73c98ea27a32c61d4ea34ef0651
