apiVersion: apps/v1
kind: Deployment
metadata:
  name: aladdin-genius
  namespace: marwan-dev
  labels:
    app: aladdin-genius
    developer: aladdin
    purpose: lol
spec:
  selector:
    matchLabels:
      app: genius
  replicas: 1
  template:
    metadata:
      labels:
        app: genius
    spec:
      containers:
        - name: genius-lol
          image: quay.io/idp_org/aladdin-genius:lol:sha256:bd8c5b8a31c9ad25e82e45083c78ee2e716ec29a9c90385b4cc17a8c1bec8d77
