apiVersion: apps/v1
kind: Deployment
metadata:
  name: hula-hoop
  namespace: marwan-dev
  labels:
    app: hula-hoop
    developer: hula
    purpose: spin
spec:
  selector:
    matchLabels:
      app: hoop
  replicas: 1
  template:
    metadata:
      labels:
        app: hoop
    spec:
      containers:
        - name: hoop-spin
          image: quay.io/idp_org/hula-hoop:spin:sha256:e55c2da835044fd18605900a8c4d2543026f738615013bd6fa3cbfbaac79bd3f
