apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxvf-asdf
  namespace: marwan-dev
  labels:
    app: zxvf-asdf
    developer: zxvf
    purpose: asdf
spec:
  selector:
    matchLabels:
      app: asdf
  replicas: 1
  template:
    metadata:
      labels:
        app: asdf
    spec:
      containers:
        - name: asdf-asdf
          image: quay.io/idp_org/zxvf-asdf:asdf:sha256:7d41aeded7ec0b9b06bb0fe0cab38e9bd8922d7bac25c370778e4f4f80e16bf7
