apiVersion: apps/v1
kind: Deployment
metadata:
  name: rely-rook
  namespace: marwan-dev
  labels:
    app: rely-rook
    developer: rely
    purpose: der
spec:
  selector:
    matchLabels:
      app: rook
  replicas: 1
  template:
    metadata:
      labels:
        app: rook
    spec:
      containers:
        - name: rook-der
          image: quay.io/idp_org/rely-rook:der:sha256:25fa0b322d3469fda7efbde1dbd7e24b995b432da2562ac315b7fb62856c2cd0
