apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-refused
  namespace: marwan-dev
  labels:
    app: curl-refused
    developer: curl
    purpose: connection
spec:
  selector:
    matchLabels:
      app: refused
  replicas: 1
  template:
    metadata:
      labels:
        app: refused
    spec:
      containers:
        - name: refused-connection
          image: quay.io/idp_org/curl-refused:connection:sha256:4338a2427eca827a453ee5adc648e77ddf6a4ae7be427be39f2aa4dfab3b8415
