apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasd-relyw
  namespace: marwan-dev
  labels:
    app: dasd-relyw
    developer: dasd
    purpose: ew
spec:
  selector:
    matchLabels:
      app: relyw
  replicas: 1
  template:
    metadata:
      labels:
        app: relyw
    spec:
      containers:
        - name: relyw-ew
          image: quay.io/idp_org/dasd-relyw:ew:sha256:b66ce7c3bef693238b75ff64e45fd776fb2c22453ebed4275bab23fa44174477
