apiVersion: apps/v1
kind: Deployment
metadata:
  name: lololol-lololol
  namespace: marwan-dev
  labels:
    app: lololol-lololol
    developer: lololol
    purpose: lolol
spec:
  selector:
    matchLabels:
      app: lololol
  replicas: 1
  template:
    metadata:
      labels:
        app: lololol
    spec:
      containers:
        - name: lololol-lolol
          image: quay.io/idp_org/lololol-lololol:lolol:sha256:b0c1e6922394fe65e84e3efc6d490a18a0ac825b22df224e44bca7cdf7066d23
