apiVersion: apps/v1
kind: Deployment
metadata:
  name: buzzing-ferryfya
  namespace: marwan-dev
  labels:
    app: buzzing-ferryfya
    developer: buzzing
    purpose: dev
spec:
  selector:
    matchLabels:
      app: ferryfya
  replicas: 1
  template:
    metadata:
      labels:
        app: ferryfya
    spec:
      containers:
        - name: ferryfya-dev
          image: quay.io/idp_org/buzzing-ferryfya:dev:sha256:7ec41f4ed611e90327470bb7c97eee478521375ac6f3742b89a8f97f9cbabb8f
