apiVersion: apps/v1
kind: Deployment
metadata:
  name: dexter-recked
  namespace: marwan-dev
  labels:
    app: dexter-recked
    developer: dexter
    purpose: get
spec:
  selector:
    matchLabels:
      app: recked
  replicas: 1
  template:
    metadata:
      labels:
        app: recked
    spec:
      containers:
        - name: recked-get
          image: quay.io/idp_org/dexter-recked:get:sha256:76337952428eac77c4bb57f506feafd118c58240a7550a38742c5054e9e25045
