apiVersion: apps/v1
kind: Deployment
metadata:
  name: pengli-testapp
  namespace: marwan-dev
  labels:
    app: pengli-testapp
    developer: pengli
    purpose: test
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp-test
          image: quay.io/idp_org/pengli-testapp:test:sha256:73f74e9892aa0bb072f80e25fd041696c952456b7139a8e809f222485eb96eb6
