apiVersion: apps/v1
kind: Deployment
metadata:
  name: laskdm-khalas
  namespace: marwan-dev
  labels:
    app: laskdm-khalas
    developer: laskdm
    purpose: nomore
spec:
  selector:
    matchLabels:
      app: khalas
  replicas: 1
  template:
    metadata:
      labels:
        app: khalas
    spec:
      containers:
        - name: khalas-nomore
          image: quay.io/idp_org/laskdm-khalas:nomore:sha256:4f4d4d6bb30d2435cc21375480e6dcdf7baf5067e6dce740334a2d792bc6555d
