apiVersion: apps/v1
kind: Deployment
metadata:
  name: potatohead-volcano
  namespace: marwan-dev
  labels:
    app: potatohead-volcano
    developer: potatohead
    purpose: dev
spec:
  selector:
    matchLabels:
      app: volcano
  replicas: 1
  template:
    metadata:
      labels:
        app: volcano
    spec:
      containers:
        - name: volcano-dev
          image:
            quay.io/idp_org/potatohead-volcano:dev:
