apiVersion: apps/v1
kind: Deployment
metadata:
  name: afdd-whynowork
  namespace: marwan-dev
  labels:
    app: afdd-whynowork
    developer: afdd
    purpose: purpose
spec:
  selector:
    matchLabels:
      app: whynowork
  replicas: 1
  template:
    metadata:
      labels:
        app: whynowork
    spec:
      containers:
        - name: whynowork-purpose
          image: quay.io/idp_org/afdd-whynowork:purpose:sha256:092506300c1e2a33a0bdb3447feae2e4b703619f961e145e4dcb013b9c704192
