apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-asdf
  namespace: marwan-dev
  labels:
    app: default-asdf
    developer: default
    purpose: dev
spec:
  selector:
    matchLabels:
      app: asdf
  replicas: 1
  template:
    metadata:
      labels:
        app: asdf
    spec:
      containers:
        - name: asdf-dev
          image: quay.io/idp_org/default-asdf:dev:sha256:7ae4fd372822a0d1fb8122c0ac87c8ac0331818465808fdd1b95e6e6a839b737
