apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekcod-runc
  namespace: marwan-dev
  labels:
    app: rekcod-runc
    developer: rekcod
    purpose: runc
spec:
  selector:
    matchLabels:
      app: runc
  replicas: 1
  template:
    metadata:
      labels:
        app: runc
    spec:
      containers:
        - name: runc-runc
          image: quay.io/idp_org/rekcod-runc:runc:sha256:5d306949e54e1f71745ad4f5622aa34285d5b2153ec80f4c8b9fa2fc428f7114
