apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-ad
  namespace: marwan-dev
  labels:
    app: default-ad
    developer: default
    purpose: adqw
spec:
  selector:
    matchLabels:
      app: ad
  replicas: 1
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
        - name: ad-adqw
          image: quay.io/idp_org/default-ad:adqw:sha256:feaf30119e8fba0671201d5a456c82497c7e9ffa7765387b8723103ca78c5c4b
