apiVersion: apps/v1
kind: Deployment
metadata:
  name: dew-train
  namespace: marwan-dev
  labels:
    app: dew-train
    developer: dew
    purpose: one
spec:
  selector:
    matchLabels:
      app: train
  replicas: 1
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: train-one
          image: quay.io/idp_org/dew-train:one:sha256:c26f5fc9df813b845f0f45c9daa41fba01962322b7c98d2da23cd9627769d7d3
