apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeman-rangin
  namespace: marwan-dev
  labels:
    app: pokeman-rangin
    developer: pokeman
    purpose: dev
spec:
  selector:
    matchLabels:
      app: rangin
  replicas: 1
  template:
    metadata:
      labels:
        app: rangin
    spec:
      containers:
        - name: rangin-dev
          image: quay.io/idp_org/pokeman-rangin:dev:sha256:525c63ab9b509387af5a5a1003db7ff649c99eee1d71cd709314ffd23a134b45
