apiVersion: apps/v1
kind: Deployment
metadata:
  name: paw-paw
  namespace: marwan-dev
  labels:
    app: paw-paw
    developer: paw
    purpose: build
spec:
  selector:
    matchLabels:
      app: paw
  replicas: 1
  template:
    metadata:
      labels:
        app: paw
    spec:
      containers:
        - name: paw-build
          image: quay.io/idp_org/paw-paw:build:sha256:c5bb5cfdd7f16c9d1acbd7a6521a6a419887e43b5a46a503a0cd44789587ef03
