apiVersion: apps/v1
kind: Deployment
metadata:
  name: alakhir-alakhir
  namespace: marwan-dev
  labels:
    app: alakhir-alakhir
    developer: alakhir
    purpose: final
spec:
  selector:
    matchLabels:
      app: alakhir
  replicas: 1
  template:
    metadata:
      labels:
        app: alakhir
    spec:
      containers:
        - name: alakhir-final
          image: quay.io/idp_org/alakhir-alakhir:final:sha256:7f62e53385b13b091e7e272baec0faba79020be791f2facda944f398dacb7be8
