apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinder-kindersuprise
  namespace: marwan-dev
  labels:
    app: kinder-kindersuprise
    developer: kinder
    purpose: rangin
spec:
  selector:
    matchLabels:
      app: kindersuprise
  replicas: 1
  template:
    metadata:
      labels:
        app: kindersuprise
    spec:
      containers:
        - name: kindersuprise-rangin
          image:
            quay.io/idp_org/kinder-kindersuprise:rangin:
