kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-service
  namespace: crossplane-system
  labels:
    app: user-service
    backstage.io/kubernetes-id: crossplane-rds    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: idp-user-service
          image: quay.io/minnie0531/user-sample-service
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-claim-connection-secret
                  key: endpoint
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-claim-connection-secret
                  key: port
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-claim-connection-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-claim-connection-secret
                  key: password
          imagePullPolicy: Always
      restartPolicy: Always
